### ISSUE TITLE
Does offline flag apply to dnf repos?

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/mixer-tools#626] opened 2019-10-24 23:40 UTC
Mixer will supply a default `clear` repo during initialization.  If a user supplies the `--offline` flag for all mixer commands and also supplies a local  file:// repo URL, the upstream repo is still enabled in `.yum-mix.conf` and dnf will have the option of reaching out to the online repo.  Is this the intended behavior?

**Comment by reaganlo** [comment] 2019-11-01 19:55
The following DNF commands get executed in **offline** mode:

```
- dnf --config=.yum-mix.conf -y --releasever=31290 --installroot=/tmp/MixerEmptyDirForNoopInstall061038593 --assumeno
- dnf --config=.yum-mix.conf -y --releasever=31290 repoquery -l --quiet --repo **local**
- dnf --config=.yum-mix.conf -y --releasever=31290 clean all
- dnf --config=.yum-mix.conf -y --releasever=31290 --installroot=update/image/10/full install --downloadonly
- dnf --config=.yum-mix.conf -y --releasever=31290 --installroot=update/image/10/full install
```
The last command will become obsolete with the upcoming rpm extraction PR #615
@ashleshaAtrey For the rest of the commands, can we confirm when does DNF refer to the **clear** repo given our default .yum-mix.conf is:
```
[clear]
name=Clear
failovermethod=priority
baseurl=https://cdn.download.clearlinux.org/releases/$releasever/clear/x86_64/os/
enabled=1
gpgcheck=0
timeout=45

[local]
name=Local
failovermethod=priority
baseurl=file:///<local-yum>
enabled=1
gpgcheck=0
priority=1
```

**Comment by ashleshaAtrey** [comment] 2019-11-01 20:50
currently any dnf command run in offline mode will go online (if it has access) if it is not able to do it in offline mode. If it doesn't have online access, it will fail only in download step that too after 4 attempts. It doesn't error out in resolving steps. Just prints No match for argument.
  @rchiossi is this suppose to be intended behavior? 

After merging PR #615, in offline mode it will not go online (even if it has access)  in download step and return error. For resolving packages and files, the behavior remains same as before (it will go online and resolve the files).

**Comment by reaganlo** [comment] 2019-11-09 00:29
@rchiossi Also, any reason why `mixer init --offline` prompts the user to provide a `--clear-version`?
Why can't it behave the way `mixer init --no-default-bundles --all-local` does?

**Comment by rchiossi** [comment] 2019-11-14 14:27
The way things are implemented right now, a mix is always expected to be based of something. There are many commands and internal checks that will use the value provided by `--clear-version`, like `mixer versions`. Most of those are avoided by upstream by either using the `--offline` flag or just never using the command that requires that value. Init wants a value that can be used for those cases (it doesn't know that you will be skipping them in the future), so there is no way around it. Without the offline flag, if you don't provide `--clear-version`, mixer will fetch the latest version, so that is why it works.

It might be nice to consider an `Upstream Mode` for future implementation, where we are not required to provide an upstream version and we ensure that all commands work properly on that mode. That should make the integration with distro-factory for upstream much cleaner.

**Comment by reaganlo** [comment] 2020-04-26 23:38
Conclusion: No, the offline flag does not apply to dnf repos and packages. It only applies to the fetching of bundle definition files.
      `--offline         Skip caching upstream-bundles; work entirely with local-bundles`

**Closed by reaganlo** 2020-04-26 23:38 UTC
Labels: question
