### ISSUE TITLE
Behavior when calling mixer build update twice

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#96] opened 2018-01-16 21:30 UTC
When calling 'mixer build update' twice, the second call will try to create an update from the version to itself, leading to invalid output. This happens because after the first update, LAST_VER is also updated, and that file is used as input for the update itself.

Note that calling 'mixer build chroots' twice leads to rewriting the chroots (and reseting the environment for that version).

I don't think there are legitimate cases for LAST_VER == "version we are building right now", so we should either:

a) stop the execution of the second call ("update already exists" kind of error?), maybe pointing the user of what needs to be done to re-create the updates and/or instruct about bumping mixver.
b) work like build chroots and redo the update.

In both cases, we have a problem: we overwrite the LAST_VER in the first execution, so we don't know what is the previous version.

For case (a) we still have something even without the previous LAST_VER (we just won't be able to instruct the user easily how to redo things).

**Comment by cmarcelo** [comment] 2018-01-16 21:33
My own take for the short term: we should at least error out when mixver == LAST_VER. It will produce invalid updates.

Later on we save the previous version that will allow us to tell the user how to rollback.

**Comment by tmarcu** [comment] 2018-02-22 22:41
When mixver = current ver it's technically doing a minversion build. Option B.) has historically been rejected because of reproducible build issues, and numbers are cheap so if a build did not work, skip it and move forward. I don't think re-creating the same ver should be allowed unless EVERYTHING is rebuilt, but chroots may in fact be correct, and just the update failed. In this case, we do not want to remove the chroots.
I think the best option is to automatically bump the version no matter what, so subsequent builds will not be repeated versions.

**Comment by tmarcu** [comment] 2018-07-02 16:23
Closing and will update documentation on proper workflow as needed.

**Closed by tmarcu** 2018-07-02 16:23 UTC
Labels: bug
