### ISSUE TITLE
The X509 certificate for my mix expired, how do I renew?

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/mixer-tools#579] opened 2019-05-23 18:29 UTC
Hey,

how do I renew the mix certificate? There is no documentation about that. The only piece I found is that I should not generate it manually.

My updates are currently broken, because of that.

**Comment by rchiossi** [comment] 2019-05-23 18:49
Are you relying on the self-signed certificate generated by mixer?

**Comment by mpurzynski** [comment] 2019-05-23 19:04
Yes, I am

**Comment by rchiossi** [comment] 2019-05-23 19:15
Ok, so this is gonna be a bit tricky.

The self-signed certificate in mixer was originally not intended for production use since usually those require better control over the signing process. In those cases, certificate management is done externally, so mixer doesn't need to worry about expiring certs. The self-signed certificate was intended to facilitate testing and development, and as such, never required management of the certificate since those mixes are short lived. Now, that doesn't mean that you cannot use the built in function, it just means that at the moment there are no certificate management features implemented in mixer.

The problem right now is that you need to update the certificate in your mix to generate the new update, but once you do, the certificate installed on the client will not be able to validate this new cert.

The best solution is to update your certificate and manually perform the update on the target using `swupd update --nosigcheck`. Another option would be to roll back the clock.

Unfortunately I can't think of a work around that won't require manual intervention.

@otaviobp Do you have any other suggestion on how he could fix his mix?

**Comment by mpurzynski** [comment] 2019-05-23 19:27
How do I generate my own certificate to make it compatibile with ClearLinux, though? The mixer documentation advises against it, that's why I am confused.

I can use some more "enterprise" certificate management as long as as I know what's required.

A one-time intervention of clients is OK. What I will do is I will use our ansible roles to update the certificate on our clients that use this mix.

**Comment by rchiossi** [comment] 2019-05-23 19:33
The easy way to generate a new one is to just create a new mix in a new folder and copy the newly generated .pem files over to your mix.
`mixer init && sudo mixer build bundles --native`
The certs are generated at the very beginning of the build bundles steps, so you can kill the build afterwards.
After replacing the certs, and generating the chroots for the new update, just double check and make sure the certificate in the chroot is the new one you just copied over.

**Comment by mpurzynski** [comment] 2019-05-23 21:15
What about generating new certificate with openssl? Is there anything special I need to take into account?

**Comment by rchiossi** [comment] 2019-05-24 14:22
Actually mixer use openssl binary to generate the certs. You can check the command line used here:
https://github.com/clearlinux/mixer-tools/blob/5228ca564979a06f47b396245b5758da8c8341ca/builder/update.go#L39

I am not sure if there are other options of cert/validation that can be used, but I believe so. @otaviobp should have more information about this.

**Comment by reaganlo** [comment] 2020-03-12 14:34
All questions have been addressed. Closing.

**Closed by reaganlo** 2020-03-12 14:34 UTC
Labels: question
