### ISSUE TITLE
Mixer needs to be able to set a persistent --offline option in the builder.conf

### ISSUE THREAD

**Issue by tmarcu** [clearlinux/mixer-tools#453] opened 2018-10-08 19:18 UTC
Some users are pure upstreams, meaning they do not **EVER** want to go online for any mixer operation. The content and infrastructure even for regular downstream users may require them to work locally only because of network issues/security, so making this persist without having to constantly call the flag on every command will be required.

**Comment by rchiossi** [comment] 2018-10-09 17:47
I can incorporate this in my current patch since I'm already working on --offline code paths.

**Comment by LibertadCruz** [comment] 2018-10-31 22:38
some TC that come to mind.

1.Generate a working directory with mixer --offline option enabled and persistent. Add bundles and build, disable any connection to the outer network. 


a.Expected result: Mixer should never try to connect or fail.


2.Execute step 1 then Update your Clear linux version using swupd update, then mix, add bundles, remove, build.


a.Expected result: Again mixer should not attempt to connect upstream.


3.Execute step 1 then Update even into another format bump, try to mix, add bundles, build.


a.Expected result: again mixer should not attempt to connect upstream.


4.Execute step 1 then, try unsetting the offline flag, mix, build, add remove bundles. Then try to set the permanent --offline flag.


Expected result: Mixer should connect when offline flag is unset and not connect when it is set. Mixer should be able to set and unset this flag at users will.

**Comment by tmarcu** [comment] 2018-11-19 19:20
@rchiossi can you write some updates on this?

**Comment by rchiossi** [comment] 2018-11-20 12:38
There are currently 3 things left to get persistent offline working:
1: Finish #460 as it will allow offline mode to be toggled
2: Fix `--offline` in `mixer versions` subcommand.
3: Make the config persistent on init.

I'm finishing item 1 and item 3 is trivial once the rest is in. I already have bat tests ready for this and I've also tested mixer.state conversion once the property is added. The only thing that might take some time is item 2. The problem is preserving the current text output of that command, but if we don't care too much about it and just force set in offline mode, then the fix is also quite simple.

I believe there is no big blocker that would prevent us from having it integrated by next release.

**Comment by tmarcu** [comment] 2018-11-20 19:00
@rchiossi great, I agree with your plan ^
I probably won't get a chance to release until next week because of the holidays here & I want to continue having QA and devops available, but we can always merge and run a build on the test infra so we can release quickly on Monday again.

**Comment by reaganlo** [comment] 2019-10-30 18:45
@rchiossi If this is not a requirement any more, can we close this?

**Comment by gtkramer** [comment] 2019-10-30 18:51
From the upstream side, this is not a requirement anymore.  Automation that we're writing with clr-distro-factory will be written in a way to easily accommodate this as it is today.  Plus, the number of upstream users is going to be very very small.  And if there are others, we'll be referring them to clr-distro-factory.  I'd also like to see this option not be more cemented into mixer's configuration in response to #627.

**Comment by rchiossi** [comment] 2019-10-30 19:06
Yes, i believe we can close this one. As George stated, our requirements have changed.

**Closed by rchiossi** 2019-10-30 19:06 UTC
Labels: enhancement, high-priority

**Comment by gtkramer** [comment] 2019-10-30 20:08
Requirement removed by https://github.com/clearlinux/clr-distro-factory/pull/51
