### ISSUE TITLE
Only docker runc runtime is supported due to use of --host networking; phy device removed with kata or cc-runtime

### ISSUE THREAD

**Issue by aenertia** [clearlinux/mixer-tools#400] opened 2018-08-14 02:51 UTC
doing a simple swupd-add-pkg will cause the NIC interface to be removed from the host OS if using a runtime other than runc (as is the case with the default containers bundle or kata).

This makes the mixer not only un-usable but dangerous to use when using it in combination with any of the above as a PCI VFIO mask is applied during a normal run i.e

swupd-add-pkg linux-firmware will result in an off-line system with no NIC interface present in the base kernel userspace. 

Suggest implementing a check/force to use of runc as part of the programme.

**Comment by tmarcu** [comment] 2018-08-14 22:11
swupd-add-pkg is deprecated, please see the `mixin` binary that is now provided with mixer.

**Comment by rchiossi** [comment] 2018-08-14 22:28
@aenertia  It would also be helpful to have a full description of the commands you are running so we can try to reproduce it on our side.

**Comment by tmarcu** [comment] 2018-08-14 22:36
@aenertia `swupd-add-pkg` is still calling mixer directly (it should have been removed from the swupd-client package...), which by default runs in a container as of version 5.0.0+. The `mixin` binary calls the mixer API internally and *does* run natively by default, so you should not see any container errors with mixin.
However, this still outlines an issue that mixer is not compatible with the kata runtime, so if you can give us some more info to debug this that would be very helpful!

**Comment by matthewrsj** [comment] 2018-08-15 17:19
Yeah I'll remove swupd-add-pkg from swupd-client...

**Comment by aenertia** [comment] 2018-08-15 18:51
Not just kata but container-c also.
It's due to the chain of events which relate to how -host networking is
attempted with container-c or kata runtimes which result in an attempt to
do a device passthrough of the NIC. Easiest to just install the container
bundle of a fresh baremetal install and see for yourself  - that box is now
doing $stuff and I'm not about to start dropping NIC to reproduce ;0)

**Comment by tmarcu** [comment] 2018-08-15 19:10
I'm not sure this is mixer related tbh, I can't imagine why running a mixer container specifically would remove your *host* NIC... did you open an issue with kata? I can poke the right people otherwise to investigate this more...

**Comment by egernst** [comment] 2018-08-15 19:17
kata-runtime should not be used with host networking.  This is a known limitation on Kata, and we recently introduced a patch to error out gracefully, rather than try to make it work.  See
https://github.com/kata-containers/runtime/issues/499

**Comment by aenertia** [comment] 2018-08-15 19:30
Yes I am well aware of Kata limitations right now; I just wasn't expecting
to hit this when doing a trivial add of a package.

**Comment by aenertia** [comment] 2018-08-15 19:33
As an introduction to the distro it was pretty jarring.

**Comment by egernst** [comment] 2018-08-15 19:34
Yeah, I think the reason you hit it is because Kata is set as the default, and we don't error out very nicely in the release that's included in Clear Linux.  Any program which expects to just work with a container with host access will fall over nicely right now.  We're talking through right now what the best way to set this up is (either have mixins specifically request runc, or to have the default runtime select runc).

**Comment by tmarcu** [comment] 2018-08-15 20:04
@aenertia What you are doing is **_not_** a trivial process. The `swupd-add-pkg `(now `mixin`) enables a very specific use case of adding content that is not provided by upstream to your official image without forking you off the update stream.
The OS is tied to a specific upstream which does a multitude of things during an update or content add, which includes security verification and hash checking to ensure that content you get is actually coming from *upstream* and not some rogue source AND will not conflict. Adding a package to your official image that is not part of the upstream source while ensuring you are still able to continue updating with the regular upstream release cadence means having to check that no conflicts exist between what you are adding and upstream, building a small custom mix (which is nicely hidden from you as mixer runs build bundles & build custom update content automatically), and then merging it into a single format that the swupd client can consume and correctly multiplex between two sources: upstream, and your own update repo. 

This is a still developing feature that we added so users don't have to create a full mix to test small changes within a Clearlinux image. If there's a lot of content you would like to provide and curate, I suggest looking into just running mixer itself and creating your own image & updates for it; it's much more stable and supported, and more accurately represents a build & release environment.

*Going forward - I will set it to always force runc for mixer & update the documentation stating it will do so. It will still crash if it's not available on the system, but unless the user removes it that shouldn't be an issue.

**Comment by aenertia** [comment] 2018-08-15 20:14
I am still flumoxed that the included openvswitch does NOT include dpdk
(after figuring out how to pull spec files of the included version I
discovered there were dpdk config options, but gave up as figuring out how
to rebuild and specify that in the spec was at the end of a long struggle
with the out of date guides/docs) - which was the motivation here. I gave
up and reverted to a custom openwrt build.

**Comment by tmarcu** [comment] 2018-08-21 09:03
Fixed by 26fe8cec9313f5daa6b339276aef019b5a1f9053

**Closed by tmarcu** 2018-08-21 09:03 UTC
