### ISSUE TITLE
Do not print format warning when using format parameter

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/mixer-tools#532] opened 2019-01-15 19:40 UTC
```
+ mixer build update --offline --config builder.conf --min-version 27210 --format 27 --no-publish --no-signing --native
Warning: Using FORMAT value from /usr/share/defaults/swupd/format
```
When passing the `--format 27` option at the command line, it does not appear to be honored and instead, mixer appears to use the system-installed format.  The intended behavior is that anything defined on the command line overrides anything in a config file or any fallback pattern.

**Comment by rchiossi** [comment] 2019-01-15 20:03
From what I can see in the code, mixer is using the value in `--format`, the problem is that the warning is misplaced. This warning is printed when mixer creates a new mixer.state file, but that happens before the format value is overwritten by the command line parameter. Behavior is good, we need to fix the error message.

**Comment by reaganlo** [comment] 2020-05-27 22:48
Fixed in v6.2.4

**Closed by reaganlo** 2020-05-27 22:48 UTC
